name       : gnuchess
version    : 6.2.9
release    : 10
source     :
    - https://ftp.gnu.org/gnu/chess/gnuchess-6.2.9.tar.gz : ddfcc20bdd756900a9ab6c42c7daf90a2893bf7f19ce347420ce36baebc41890
homepage   : https://www.gnu.org/software/chess/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU Chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
