name        : gnuchess
version     : 6.2.1
release     : 3
source     :
    - http://ftp.gnu.org/gnu/chess/gnuchess-6.2.1.tar.gz : 17caab725539447bcb17a14b17905242cbf287087e53a6777524feb7bbaeed06
license     :
    - GPLv3+
summary     : GNU Chess program
description : |
    GNU chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
