name       : gnuchess
version    : 6.2.3
release    : 5
source     :
    - http://ftp.gnu.org/gnu/chess/gnuchess-6.2.3.tar.gz : 78999176b2f2b5e0325bcc69749b7b2cefb7b1ef4f02d101fa77ae24a1b31b82
license    : GPL-3.0
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
