name       : gnuchess
version    : 6.2.7
release    : 8
source     :
    - https://ftp.gnu.org/gnu/chess/gnuchess-6.2.7.tar.gz : e536675a61abe82e61b919f6b786755441d9fcd4c21e1c82fb9e5340dd229846
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU Chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
