name        : gnuchess
version     : 6.2.2
release     : 4
source     :
    - http://ftp.gnu.org/gnu/chess/gnuchess-6.2.2.tar.gz : 7776c114eeb5889dea69dc4715a3622ec57f65efab667987e7d7183cc05381a8
license     :
    - GPLv3+
summary     : GNU Chess program
description : |
    GNU chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
