name       : gnuchess
version    : 6.2.4
release    : 6
source     :
    - https://ftp.gnu.org/gnu/chess/gnuchess-6.2.4.tar.gz : 3c425c0264f253fc5cc2ba969abe667d77703c728770bd4b23c456cbe5e082ef
license    : GPL-3.0
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
