name       : gnuchess
version    : 6.2.5
release    : 7
source     :
    - https://ftp.gnu.org/gnu/chess/gnuchess-6.2.5.tar.gz : 9a99e963355706cab32099d140b698eda9de164ebce40a5420b1b9772dd04802
license    : GPL-3.0
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
